[tool.poetry]
name = "flask-learning"
version = "0.1.0"
description = ""
authors = ["shih_jun_teh <shih_jun_teh@dell.com>"]

[tool.poetry.dependencies]
python = "^3.7"
flask = "^1.1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
